---
- hosts: localhost
  connection: local
  become: true
  tasks:
    - name: install helm if it does not exist
      unarchive:
        src: https://get.helm.sh/{{ helm_version }}
        dest: /usr/local/bin
        extra_opts: --strip-components=1
        owner: root
        group: root
        mode: 755
        remote_src: true
      args:
        creates: /usr/local/bin/helm
    - name: Update all Debian/Ubuntu packages to their latest version
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
        name: "*"
        state: latest
      when:
        - ansible_distribution in ["Debian", "Ubuntu"]
    - name: Update all RedHat/CentOs/Rocky packages to their latest version
      ansible.builtin.dnf:
        update_cache: true
        name: "*"
        state: latest
      when:
        - ansible_distribution in ["Rocky", "CentOs" ,"RedHat"]
    - name: Remove podman
      shell: |
        dnf remove podman.x86_64 -y
        dnf autoremove -y
      when:
        - ansible_distribution in ["Rocky", "CentOs" ,"RedHat"]
    - name: Uninstall old versions
      dnf:
        name:
          - docker-client
          - docker-client-latest
          - docker-common
          - docker-latest
          - docker-latest-logrotate
          - docker-logrotate
          - docker-engine
        state: absent
      when:
        - ansible_distribution in ["Rocky", "CentOs" ,"RedHat"]
    - name: Set up docker repository for Rocky
      shell: |
        dnf install -y yum-utils
        yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      args:
        warn: no
      when:
        - ansible_distribution in ["Rocky", "CentOs" ,"RedHat"]
    - name: Set up docker repository for Ubuntu
      shell: |
        apt install -y curl gnupg2 software-properties-common apt-transport-https ca-certificates 
        curl -fsSL  https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - 
        add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      when:
        - ansible_distribution in ["Debian", "Ubuntu"]
    - name: Install the latest version of Docker Engine and containerd all OS
      package:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
    - name: Add the current user to the docker group
      user:
        name: aca
        groups: docker
        append: yes
    - name: Start and enable docker
      systemd:
        name: docker
        state: started
        enabled: yes
