

---
 - hosts: localhost
   connection: local
   become: true
   

   tasks:
   - name: install helm if it does not exist
     unarchive:
        src: https://get.helm.sh/{{ helm_version }}
        dest: /usr/local/bin
        extra_opts: "--strip-components=1"
        owner: root
        group: root
        mode: 0755
        remote_src: true
     args:
      creates: /usr/local/bin/helm

   - name: Update all Debian/Ubuntu packages to their latest version
     ansible.builtin.apt:
                update_cache: true
                cache_valid_time: 3600
                name: "*"
                state: latest
     when: 
       - ansible_distribution in ["Debian", "Ubuntu"]

    - name: Update all RedHat/CentOs/Rocky packages to their latest version
     ansible.builtin.dnf:
                update_cache: true
                cache_valid_time: 3600
                name: "*"
                state: latest
     when: 
       - ansible_distribution in ["Rocky", "CentOs" ,"RedHat"]
    