

---
 - hosts: localhost
   connection: local
   become: true

   tasks:
   - name: download helm
     package:
       name:
         - htop
         - tmux
         - vim-nox
    #ansible.builtin.uri:
    #url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
   # return_content: true
   # register: helm_installer

  #- name: Install Helm
    #ansible.builtin.command:
  # cmd: bash
   # stdin: "{{ helm_installer.content }}"
   # creates: /usr/local/bin/helm
   # environment:
   # DESIRED_VERSION: "{{ helm_version | default('') }}"

  #- name: install prereq packages for Kubernetes
    #package:
      #name:
      #  - curl
     #   - apt-transport-https
     #when: ansible_distribution in ["Debian", "Ubuntu"]