

---
 - hosts: localhost
   connection: local
   become: true

   tasks:
   - name: install helm if it does not exist
     unarchive:
        src: https://get.helm.sh/helm-v3.11.0-linux-amd64.tar.gz
        dest: /usr/local/bin
        extra_opts: "--strip-components=1"
        owner: root
        group: root
        mode: 0755
        remote_src: true
     args:
      creates: /usr/local/bin/helm