---
 - hosts: localhost
   connection: local
   become: true
 
   tasks:
   - name: install prereq packages for Kubernetes
     package:
       name:
         - helm
         - curl
         - apt-transport-https
     #when: ansible_distribution in ["Debian", "Ubuntu"]